# Generated by Django 2.1.7 on 2019-07-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelsA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleA', models.CharField(max_length=255)),
                ('imageA', models.ImageField(upload_to='images/')),
                ('descriptionA', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TravelsC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleC', models.CharField(max_length=255)),
                ('imageC', models.ImageField(upload_to='images/')),
                ('descriptionC', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TravelsL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleL', models.CharField(max_length=255)),
                ('imageL', models.ImageField(upload_to='images/')),
                ('descriptionL', models.CharField(max_length=500)),
            ],
        ),
    ]
